// List of available courses (expand as needed)
export const COURSE_LIST = [
  { code: "CS201", name: "Data Structures" },
  { code: "CS301", name: "Databases" },
  { code: "CS202", name: "Operating Systems" },
  { code: "SE301", name: "Software Engineering" },
  { code: "CS204", name: "Algorithms" },
  { code: "CS205", name: "Computer Networks" },
  { code: "CS206", name: "Artificial Intelligence" },
  { code: "CS207", name: "Machine Learning" },
  { code: "CS208", name: "Web Development" },
  { code: "CS209", name: "Mobile App Development" },
  { code: "CS210", name: "Cyber Security" },
  { code: "CS211", name: "Cloud Computing" },
  { code: "CS212", name: "Human Computer Interaction" },
  { code: "CS213", name: "Software Project Management" },
  { code: "CS214", name: "Discrete Mathematics" },
  { code: "CS215", name: "Compiler Construction" },
  { code: "CS216", name: "Digital Logic Design" },
  { code: "CS217", name: "Operating Systems Lab" },
  { code: "CS218", name: "Database Systems Lab" },
  { code: "CS219", name: "Data Science" },
  { code: "CS220", name: "Information Retrieval" },
  { code: "CS221", name: "Parallel Computing" },
  { code: "CS222", name: "Computer Graphics" },
  { code: "CS223", name: "Numerical Computing" },
  { code: "CS224", name: "Digital Image Processing" },
  { code: "CS225", name: "Pattern Recognition" },
  { code: "CS226", name: "Natural Language Processing" },
  { code: "CS227", name: "Big Data Analytics" },
  { code: "CS228", name: "Blockchain" },
  { code: "CS229", name: "IoT" },
  { code: "CS230", name: "Embedded Systems" },
];
